spacetelescope/hstcal

pkg/wfc3/calwf3/wf32d/wf32d.c

Joe - this should update hstcal/wfc3 to match with the opus_2015_3dms delivery

update to sync opus_2015_3dms change with master

---

pkg/wfc3/calwf3/Dates
pkg/wfc3/calwf3/History
pkg/wfc3/calwf3/Updates
pkg/wfc3/calwf3/calwf3/procccd.c
pkg/wfc3/calwf3/include/wf3version.h

one more mem allocation fix for wf3rej

one more fix for wf3rej before release

---

pkg/acs/calacs/lib/prinfo.c

https://jira.stsci.edu/browse/HCD-8

HCD-8 Uninitialized variable 'i' in calacs prinfo.c

---

pkg/acs/calacs/lib/prinfo.c

Reverts spacetelescope/hstcal#24

Revert "HCD-8 Uninitialized variable 'i' in calacs prinfo.c"

---

pkg/acs/calacs/acsccd/doblev.c

Add diagnostic message for BLEVCORR to aid #31. Going to merge this immediately.

Add diagnostic message for BLEVCORR

---

.travis.yml

Initial commit of Travis-CI configuration

---

wscript

Have gcc supersede clang when finding C compiler

---

pkg/wfc3/calwf3/Dates
pkg/wfc3/calwf3/History
pkg/wfc3/calwf3/Updates
pkg/wfc3/calwf3/include/wf3version.h
pkg/wfc3/calwf3/wf32d/doflux.c
pkg/wfc3/calwf3/wf32d/dophot.c

This updates the descriptions for UVIS header photometry keywords. Finalized descriptions will be made soon. Local tests passed for me and only keyword descrips showed change.
see #67

staging: photometry keyword updates for wfc3 uvis 

---

hstio/hstio.c

This is the cleaner pull request for sara's changes for comparison with the original pull

Sara ogaz comment bug fix

---

hstio/hstio.c
include/hstio.h

Adds the struct:
PtrRegister
and the folowing 'methods'
void initPtrRegister(PtrRegister * reg);
void addPtr(PtrRegister * reg, void * ptr, void * freeFunc); // ptr list is self expanding
void freePtr(PtrRegister * reg, void * ptr);
void freeOnExit(PtrRegister * reg); //only calls freeAll() followed by freeReg()
void freeAll(PtrRegister * reg); // frees all ptrs registered (excluding itself)
void freeReg(PtrRegister * reg); // frees itself i.e. the register array holding the ptrs
Fixes #81

Add pointer register for memory allocation book keeping

---

.gitignore
pkg/acs/calacs/Dates
pkg/acs/calacs/History
pkg/acs/calacs/Updates
pkg/acs/calacs/acsccd/doblev.c
pkg/acs/calacs/acsccd/doccd.c
pkg/acs/calacs/acsccd/dosink.c
pkg/acs/calacs/acsccd/findover.c
pkg/acs/calacs/acsccd/getacsflag.c
pkg/acs/calacs/acsccd/getccdsw.c
pkg/acs/calacs/cfiles.log
pkg/acs/calacs/include/acsinfo.h
pkg/acs/calacs/include/acsversion.h
pkg/acs/calacs/lib/wscript

Reverts spacetelescope/hstcal#105

Revert "Revert all pllims 2017.2 acs changes"

---

ctegen2/ctegen2.c
ctegen2/ctegen2.h
ctegen2/ctehelpers.c
ctegen2/wscript
pkg/acs/calacs/Dates
pkg/acs/calacs/History
pkg/acs/calacs/acscte/acscte.c
pkg/acs/calacs/acscte/docte.c
pkg/acs/calacs/acscte/dopcte-gen2.c
pkg/acs/calacs/acscte/dopcte.c
pkg/acs/calacs/acscte/getcteflag.c
pkg/acs/calacs/acscte/maincte.c
pkg/acs/calacs/acscte/pcte.h
pkg/acs/calacs/acscte/pcte_fixycte.c
pkg/acs/calacs/acscte/pcte_funcs.c
pkg/acs/calacs/acscte/wscript
pkg/acs/calacs/calacs/acsmain.c
pkg/acs/calacs/calacs/calacs.c
pkg/acs/calacs/calacs/calacs.h
pkg/acs/calacs/include/acsinfo.h
pkg/acs/calacs/include/acsversion.h
pkg/acs/calacs/lib/acsinfo.c
pkg/acs/calacs/lib/ucalver.c
pkg/acs/calacs/lib/wscript
wscript

This reverts commit bf8c64a8fac8efef4c6e982054f3fb3c7d3c7b05.

Revert "Revert "ACS CTE second generation correction algorithm""

---

ctegen2/ctegen2.c

Algorithm bug introduced from #112

---

pkg/acs/calacs/acscte/docte.c
pkg/acs/calacs/include/acs.h

ACS CTE: Default to gen 2 and error if gen1 PCTETAB file detected

---

hstio/hstio.c

Memory corruption in PtrRegister::freeReg()

---

hstio/hstio.c
include/hstio.h

Refactor PtrRegister to correctly handle 'this' pointers

---

hstio/hstio.c

PtrRegister: freePtr() assumes ptr passed has definitely been added

---

pkg/acs/calacs/acscte/dopcte-gen2.c

ACS CTE - don't explicitly error on subarray image input files

---

pkg/acs/calacs/calacs/acsmember.c
pkg/acs/calacs/calacs/acstable.c
pkg/acs/calacs/include/acs.h
pkg/acs/calacs/lib/findroot.c

Buffer overflow - CALACS fix only

---

ctegen2/ctehelpers.c
pkg/acs/calacs/acscte/dopcte-gen2.c
pkg/acs/calacs/include/acs.h

Fix ACS CTE for subarrays

---

pkg/acs/calacs/acssum/mainsum.c

Unguarded IF in ACS SUM mainsum.c - missing {}

---

pkg/wfc3/calwf3/wf32d/do2d.c

Unguarded IF in wf32d/do2d.c

---

include/hstcalversion.h
lib/hstcalversion.c
lib/wscript
pkg/acs/calacs/acs2d/main2d.c
pkg/acs/calacs/acsccd/mainccd.c
pkg/acs/calacs/acscte/maincte.c
pkg/acs/calacs/acsrej/mainrej.c
pkg/acs/calacs/acssum/mainsum.c
pkg/acs/calacs/calacs/acsmain.c
pkg/acs/calacs/lib/trlbuf.c
pkg/acs/calacs/lib/wscript
pkg/stis/calstis/cs0/cs0.c
pkg/stis/calstis/cs1/cs1.c
pkg/stis/calstis/cs11/cs11.c
pkg/stis/calstis/cs12/cs12.c
pkg/stis/calstis/cs4/cs4.c
pkg/stis/calstis/cs7/cs7.c
pkg/stis/calstis/cs8/cs8.c
pkg/stis/calstis/lib/wscript
pkg/wfc3/calwf3/calwf3/wf3main.c
pkg/wfc3/calwf3/lib/trlbuf.c
pkg/wfc3/calwf3/lib/wscript
pkg/wfc3/calwf3/wf32d/main2d.c
pkg/wfc3/calwf3/wf3ccd/mainccd.c
pkg/wfc3/calwf3/wf3cte/maincte.c
pkg/wfc3/calwf3/wf3ir/mainir.c
pkg/wfc3/calwf3/wf3rej/mainrej.c
pkg/wfc3/calwf3/wf3sum/mainsum.c
wscript

Add git tag version, branch, & commit to waf configure and into C code

---

ctegen2/ctegen2.h
ctegen2/ctehelpers.c

Remove usage of "UVIZ" from common CTE code

---

wscript

Error on build if --gitinfo different from that when configured

---

wscript

'make distclean' should do a 'make clean' first

---

cfitsio/drvrnet.c

Make cfitsio/drvnet.c UTF-8 compliant

---

wscript

Swap configure msg labels for git commit and git branch

---

ctegen2/ctehelpers.c
include/imphttab.h
pkg/acs/calacs/acscte/pcte.h
tables/c_imt.c
tables/c_tbfpri.c
tables/c_tbhgt.c
tables/c_tbtcre.c
tables/c_tbtopn.c
tables/ctables.c
tables/ctables.h
tables/tbl_util.c

These changes should have been contained by #209
Resolves #212

Dedup CHAR_LINE_LENGTH & CHAR_FANME_LENGTH macro defs

---

hstio/hstio.c

PtrRegister should not leak on assert()

---

lib/hstcal_memory.c

Fix typo from #250

---

ctegen2/ctegen2.h
ctegen2/ctehelpers.c
include/hstcal_memory.h
lib/hstcal_memory.c

Move memory functions from ctehelpers.c to lib/hstcal_memory.c

---

wscript

 Hard-wire git describe --abbrev digits to the documented default of 7

---

wscript

Script yanked from WAF's documentation:
- https://waf.io/apidocs/_modules/waflib/Tools/fc_config.html
Improvements:
- `./waf configure` now performs a generic scan for OpenMP rather than assuming `-fopenmp` is the only flag in town.
- Permits `clang`'s native OpenMP library to link without manual modification of the `wscript` (see: https://openmp.llvm.org/)
- Makes more sense.
Resolves #256

[configuration] Support more than one OpenMP implementation

---

pkg/wfc3/calwf3/calwf3/calwf3.h
pkg/wfc3/calwf3/calwf3/wf3member.c
pkg/wfc3/calwf3/calwf3/wf3table.c
pkg/wfc3/calwf3/include/wf3info.h
pkg/wfc3/calwf3/lib/findroot.c
pkg/wfc3/calwf3/wf3sum/wf3sum.c

Issue 150 - Buffer overflow

---

pkg/stis/calstis/cs1/cs1.c
pkg/stis/calstis/cs11/cs11.c

Fixes #280
Regression introduced from #275

Remove incorrect non-ptr registrations

---

pkg/acs/calacs/calacs/acsdth.c
pkg/acs/calacs/calacs/calacs.c
pkg/acs/calacs/lib/mkspt.c

This reverts commit 4cd1b461e79e72202440114026e806ccd5102d20.
Resolves #290

Revert "CALACS: Clarifies error/warning messages for SPT files."

---

pkg/acs/calacs/Dates
pkg/acs/calacs/History
pkg/acs/calacs/Updates
pkg/acs/calacs/acsrej/acsrej_check.c
pkg/acs/calacs/acsrej/acsrej_do.c
pkg/acs/calacs/acsrej/acsrej_init.c
pkg/acs/calacs/acsrej/acsrej_loop.c
pkg/acs/calacs/acsrej/acsrej_sky.c
pkg/acs/calacs/acsrej/readpar.c

**You can merge this once approval is obtained from ACS Team.**
See:
https://trac.stsci.edu/ssb/stsci_python/ticket/598
https://trac.stsci.edu/ssb/stsci_python/ticket/976
https://trac.stsci.edu/ssb/stsci_python/ticket/1223
https://trac.stsci.edu/ssb/stsci_python/ticket/1224
**Instructions to install this branch for testing**
1. Create a directory to store the source codes and `cd` into it. (If you have done it before for another PR, just `cd` into it your existing directory.)
2. `git clone https://github.com/pllim/hstcal.git ./` (this makes a copy of my HSTCAL fork on your disk, skip this if you already cloned it before for another PR)
3. `git fetch origin lim-calacs-ticket976`
4. `git checkout origin/lim-calacs-ticket976 -b lim-calacs-ticket976` (if this does not work, your `git` version …

New ACSREJ algorithm and bug fixes

---

pkg/acs/calacs/Dates
pkg/acs/calacs/History
pkg/acs/calacs/Updates
pkg/acs/calacs/include/acsversion.h
pkg/stis/calstis/include/stisversion.h
pkg/wfc3/calwf3/Dates
pkg/wfc3/calwf3/History
pkg/wfc3/calwf3/Updates
pkg/wfc3/calwf3/include/wf3version.h

Signed-off-by: Michele De La Pena <mdelapena@stsci.edu>

Bumping version numbers

---

pkg/acs/calacs/acsrej/acsrej_loop.c

Fixes #299
Signed-off-by: Michele De La Pena <mdelapena@stsci.edu>

ACS:Added missing ERR header for constant value images

---

hstio/hstio.c
include/hstio.h
pkg/acs/calacs/lib/getacskeys.c

Use findTotalNumberOfImsets() to compute ACSInfo::nimsets

---

Jenkinsfile
JenkinsfileRT
README.md

build_mode -> name
Use utility library to manage conda
Force python 3.6

Adjustments for use on the RT Jenkins instance.

---

pkg/wfc3/calwf3/wf3cte/wf3cte.c

WFC3 CTE - fix out of bounds memory access

---

pkg/wfc3/calwf3/include/wf3version.h

Bump calwf3 ver to 3.5.0

---

JenkinsfileRT

DOC: Fix typo in JenkinsfileRT 

---

JenkinsfileRT

JenkinsfileRT (nightly run) will open issue on failure with this patch.

TST: JenkinsfileRT will open issue on failure

---

JenkinsfileRT
tests/helpers.py

Fix #388 
p.s. Not sure how to test this without merging. Maybe we should just merge and see what happens. Any ideas , @rendinam and @jhunkeler ?

TST: Add functionality to upload artfifact

---

README.md
pytest.ini

Update RT link

---

Jenkinsfile
JenkinsfileRT

As not to eat up all the cores.

Jenkins to only use 4 threads for CTE correction

---

.readthedocs.yml

Correct problem with yml file for docs.

Fix path to docs yml file

---

.readthedocs.yml

Another attempt to get the configuration correct for the RTD doc build.

Try to get the configuration correct...again

---

docs/.rtd-environment.yml

Revise more RTD environment configuration files.

Try rtd setup again

---

tests/wfc3/test_uvis_10single.py
tests/wfc3/test_uvis_11single.py
tests/wfc3/test_uvis_12single.py
tests/wfc3/test_uvis_13single.py
tests/wfc3/test_uvis_14single.py
tests/wfc3/test_uvis_15single.py
tests/wfc3/test_uvis_16single.py
tests/wfc3/test_uvis_17single.py
tests/wfc3/test_uvis_19single.py
tests/wfc3/test_uvis_20single.py
tests/wfc3/test_uvis_21single.py
tests/wfc3/test_uvis_22single.py
tests/wfc3/test_uvis_23single.py
tests/wfc3/test_uvis_25single.py
tests/wfc3/test_uvis_28single.py
tests/wfc3/test_uvis_29single.py
tests/wfc3/test_uvis_30single.py
tests/wfc3/test_uvis_31single.py
tests/wfc3/test_uvis_32single.py

These changes address Issue #458.

Streamlined regression tests

---

wscript

Fix #472 
Works for me but someone needs to check the `waf` syntax.

MNT: Enforce C99

---

wscript

`platform.popen` was removed in Python 3.8

Stop using platform.popen()

---

.travis.yml

TST: Travis shall pass

---

pkg/acs/calacs/Dates
pkg/acs/calacs/History
pkg/acs/calacs/Updates
pkg/acs/calacs/acsrej/acsrej_loop.c
pkg/acs/calacs/acsrej/piksrt.c
pkg/acs/calacs/include/acsversion.h
pkg/stis/calstis/cs2/piksrt.c
pkg/stis/calstis/cs6/idtalg/calstis6idt.c
pkg/stis/calstis/cs6/poly.c
pkg/wfc3/calwf3/Dates
pkg/wfc3/calwf3/History
pkg/wfc3/calwf3/Updates
pkg/wfc3/calwf3/include/wf3version.h
pkg/wfc3/calwf3/wf3ir/numrec.c
pkg/wfc3/calwf3/wf3rej/piksrt.c

Modified HSTCAL infrastructure routines for ACS, WFC3, and STIS which have copyright issues.

Issue hla 255 - Address issues associated with routines under copyright

---

hstio/test/test_hstio.py

- changed pyfits --> astropy.io.fits
- fixed python-2 print statements
- closing HDUs
EDIT: Fix #524

#524: Fix "./waf test"

---

pkg/wfc3/calwf3/Dates
pkg/wfc3/calwf3/History
pkg/wfc3/calwf3/Updates
pkg/wfc3/calwf3/include/wf3info.h
pkg/wfc3/calwf3/include/wf3version.h
pkg/wfc3/calwf3/lib/getkeys.c
pkg/wfc3/calwf3/lib/wf3info.c
pkg/wfc3/calwf3/wf3cte/cte.h
pkg/wfc3/calwf3/wf3cte/getctepars.c
pkg/wfc3/calwf3/wf3cte/wf3cte.c
tests/wfc3/test_uvis_01asn.py
tests/wfc3/test_uvis_05asn.py
tests/wfc3/test_uvis_32single.py

The CTE algorithm has been significantly improved by J. Anderson.  I have only applied a light touch in that I: 
- removed many of the hard-coded values and replaced them with #define or used values already defined in wf3.h,
- made sure Jay's comments were included in the code in appropriate places, 
- marked out-of-date routines as DEPRECATED though they are still resident in the code for reference at this time, and
- fixed location of some ending braces for readability.

CTE improvements

---

pkg/wfc3/calwf3/wf3rej/mainrej.c
pkg/wfc3/calwf3/wf3rej/rej_command.c

Implemented changes to make the wf3rej component API more robust and added more extensive syntax and usage information based upon the number and type of inquiries from users.

Update wf3rej API 

---

pkg/wfc3/calwf3/Dates
pkg/wfc3/calwf3/History
pkg/wfc3/calwf3/Updates
pkg/wfc3/calwf3/include/wf3dq.h
pkg/wfc3/calwf3/include/wf3info.h
pkg/wfc3/calwf3/include/wf3version.h
pkg/wfc3/calwf3/lib/dodqi.c
pkg/wfc3/calwf3/lib/getccdtab.c
pkg/wfc3/calwf3/lib/wf3info.c
pkg/wfc3/calwf3/lib/wscript
pkg/wfc3/calwf3/wf3ccd/doccd.c
pkg/wfc3/calwf3/wf3ccd/doccd.h
pkg/wfc3/calwf3/wf3ccd/dofwsat.c
pkg/wfc3/calwf3/wf3ccd/getflags.c

Initial push of infrastructure changes to support the saturation map.  The changes thus far do NOT accommodate binning.

Basic infrastructure changes needed to support saturation map.

---

tests/stis/test_lev1_fuvspec.py

STIS/HSTCAL: Change test to g140l longslit

---

.github/workflows/cmake.yml

* Use startsWith in place of testing for exact matches in runner names

Add M1 runner

---

.github/labeler.yml
.github/workflows/open_actions_pr.yml

This auto-labels PR with the labels you already have according to the rules set in `labeler.yml`. You won't see any effect until after merge. Check the rules if you want but I have deployed this in multiple places so pretty sure it works if the rules are correct.
Also see https://github.com/actions/labeler

PR auto labeler

---

LICENSE.txt

Pretty sure hstcal existed before 2018, so I guess you are only keeping the current year, and not a range?
p.s. I mainly wanna see if the labeler works but you might as well merge this.

Update LICENSE year

---

tests/helpers.py

Fix https://github.com/spacetelescope/hstcal/issues/636
RT https://github.com/spacetelescope/RegressionTests/actions/runs/14386641621

TST: Replace find_executable with shutil.which

---

CMakeLists.txt
INSTALL.md

DOC: Clean up install instructions

---

pkg/acs/lib/acsccd/acsccd.c
pkg/acs/lib/acsccd/blevdrift.c
pkg/acs/lib/acsccd/dobias.c
pkg/acs/lib/acsccd/doblev.c
pkg/acs/lib/acsccd/doccd.c
pkg/acs/lib/acsccd/dofwsat.c
pkg/acs/lib/acsccd/getacsflag.c
pkg/acs/lib/acscte/docte.c
pkg/acs/lib/acscte/getcteflag.c
pkg/acs/lib/acsrej/acsrej_do.c
pkg/acs/lib/acsrej/cr_scaling.c
pkg/acs/lib/acsrej/readpar.c
pkg/acs/lib/bin2d.c
pkg/acs/lib/calacs/acstable.c
pkg/acs/lib/calacs/calacs.c
pkg/acs/lib/calacs/getflags.c
pkg/acs/lib/calacs/sciflags.c
pkg/acs/lib/getccdtab.c
pkg/acs/lib/mkoutname.c
pkg/acs/lib/prinfo.c
pkg/acs/lib/trim.c
pkg/acs/lib/trim2d.c
pkg/acs/src/mainsum.c

This is a direct follow-up of
* #644
RT: https://github.com/spacetelescope/RegressionTests/actions/runs/14891635050
I apologize for all the auto removal of trailing whitespace from my editor (sorry, not sorry).

Trailer file messaging clean-up

---

pkg/acs/include/calacs.h
pkg/acs/lib/calacs/acsinit.c
pkg/acs/lib/calacs/acsmember.c
pkg/acs/lib/calacs/calacs.c
pkg/acs/lib/calacs/getsciinfo.c
pkg/acs/lib/calacs/sciflags.c

Rename ACSInfo to CALACSInfo

---

pkg/acs/lib/acsccd/blev_func_main.c

Fix https://github.com/spacetelescope/hstcal/issues/679
RT: https://github.com/spacetelescope/RegressionTests/actions/runs/16541183569

BUG: Fix out of bounds overscan indexing for subarray

---

pkg/acs/Dates
pkg/acs/History
pkg/acs/Updates
pkg/acs/include/acsversion.h
pkg/acs/lib/acsccd/blev_func_main.c
pkg/acs/lib/acsccd/blev_funcs_postsm4.c
pkg/acs/lib/acsccd/dobiasshift.c

Reverts spacetelescope/hstcal#685 upon request from ACS Team because they found weird things that need further investigation.

Revert "Bias shift correction for WFC 512 and 1K subarrays"

---

tests/acs/test_wfc_sub.py

Address part of #332
RT at https://github.com/spacetelescope/RegressionTests/actions/runs/18050146941

TST: Add post-SM4 subarr bias shift test cases
