spacetelescope/hstcal

- .gitignore
- pkg/acs/calacs/Dates
- pkg/acs/calacs/History
- pkg/acs/calacs/Updates
- pkg/acs/calacs/acsccd/findover.c
- pkg/acs/calacs/include/acsversion.h
Potential fix for one of the issues documented in https://trac.stsci.edu/ssb/stsci_python/ticket/1126 . This is needed for pipeline to be able to process new 2K subarrays added by FSW change done in May 2016.
@stsci-hack , what do you think of this fix? It ran successfully on the test image. Log attached:
[jd2j15j0q.tra.txt](https://github.com/spacetelescope/hstcal/files/350949/jd2j15j0q.tra.txt)
NOTE: Also need to make sure this pass in nightly test after merging...
> CALACS BLEVCORR for new subarrays

- pkg/wfc3/calwf3/Dates
- pkg/wfc3/calwf3/History
- pkg/wfc3/calwf3/Updates
- pkg/wfc3/calwf3/include/wf3version.h
- pkg/wfc3/calwf3/wf3cte/wf3cte.c
… it had gotten moved below the header update for the information so the header keywords weren't always being populated correctly. Found during my association testing.
> Moved the init for the CTE params back to the top of the code

- pkg/wfc3/calwf3/Dates
- pkg/wfc3/calwf3/History
- pkg/wfc3/calwf3/Updates
- pkg/wfc3/calwf3/calwf3/calwf3.c
- pkg/wfc3/calwf3/calwf3/procccd.c
- pkg/wfc3/calwf3/include/wf3version.h
does not effect cte results, just memory cleanup which reared it's ugly head  in nightlys
> Fixed memory allocation around print statement

- pkg/acs/calacs/Dates
- pkg/acs/calacs/History
- pkg/acs/calacs/Updates
- pkg/acs/calacs/acsccd/findover.c
- pkg/acs/calacs/include/acsversion.h
BLEVCORR subtracts virtual overscan from polarizer and ramp using new readout format. Fixes #19. Supersedes #21.
> BLEVCORR to process new pol/ramp

- configure
Fixes:
```bash
$ make install
[...]
waf: error: no such option: --yes
make: *** [install] Error 2
```
> Remove non-existent --yes option from install target

- wscript
Removes the need to maintain a list of valid operating system versions, and their cutesy names over time. Instead, now we check whether the host operating system (OS X) is greater than or equal to 10.5.0. If not, the configuration step will fail out to the shell (i.e. exit 1). The probability of external users compiling `hstcal` on 10.4.x "Tiger" is rather low anyway at this point.
Due to subtle ambiguities we have experienced recently in the Conda world I added a visual dump for each compiler's `FLAGS` variable. This allows us to immediately determine whether C/FC/LDFLAGS were set correctly at compile-time or not.
The configuration order has changed slightly as well. CFITSIO is now configured after the global CFLAGS are defined. This allows the hidden CFITSIO `./configure` call to …
> Platform check

- pkg/acs/calacs/Dates
- pkg/acs/calacs/History
- pkg/acs/calacs/Updates
- pkg/acs/calacs/acsccd/doblev.c
- pkg/acs/calacs/acsccd/findover.c
- pkg/acs/calacs/include/acsversion.h
**Approved by ACS Team on Feb 28, 2017.**
**IMPORTANT: This must go together with new OSCNTAB delivery to CRDS!**
This is the purist way to address true overscan subtraction of subarrays. Supersedes #21 and #22. Fixes #23.
**Instructions to install this branch for testing**
1. Create a directory to store the source codes and `cd` into it.
2. `git clone https://github.com/pllim/hstcal.git ./` (this makes a copy of my HSTCAL fork on your disk)
3. `git fetch origin new-oscntab`
4. `git checkout origin/new-oscntab -b new-oscntab` (if this does not work, your `git` version is too old, so you will need to update `git` first or install a newer version using `conda install git`)
5. `git status` (if this shows that you are now in `new-oscntab` branch, then proceed)
6. `./waf configure --debug …
> BLEVCOR to use new OSCNTAB (APPROVED)

- .gitignore
- pkg/acs/calacs/Dates
- pkg/acs/calacs/History
- pkg/acs/calacs/Updates
- pkg/acs/calacs/acsccd/doccd.c
- pkg/acs/calacs/acsccd/dosink.c
- pkg/acs/calacs/acsccd/getacsflag.c
- pkg/acs/calacs/acsccd/getccdsw.c
- pkg/acs/calacs/cfiles.log
- pkg/acs/calacs/include/acsinfo.h
- pkg/acs/calacs/include/acsversion.h
- pkg/acs/calacs/lib/wscript
**Approved by Jenna Ryon from ACS Team.**
Fixes #44 
**Instructions to install this branch for testing**
1. Create a directory to store the source codes and `cd` into it.
2. `git clone https://github.com/pllim/hstcal.git ./` (this makes a copy of my HSTCAL fork on your disk)
3. `git fetch origin new-sinkcorr`
4. `git checkout origin/new-sinkcorr -b new-sinkcorr` (if this does not work, your `git` version is too old, so you will need to update `git` first or install a newer version using `conda install git`)
5. `git status` (if this shows that you are now in `new-sinkcorr` branch, then proceed)
6. `./waf configure --debug --prefix=$CONDA_PREFIX` (this only works if you use `conda env`)
7. `./waf build` (make sure there is no error)
8. `./waf install`
9. Now `cd` into your working directory …
> CALACS to have new SINKCORR in ACSCCD (APPROVED)

- .travis.yml
Fix #73 -- This uses Python 3.6 by default but also keeps tests in Python 2.7 and 3.5 to make everyone happy.
Fix #85 -- This follows the recipe somewhat from `astropy/ci-helpers`.
> Fix incorrect Python version being used in Travis

- wscript
This invokes the compiler optimization flag -O3 instead of using the current
build default -O2.
--debug takes precedence.
Use of this will spawn a warning and prompt the user for a response to continue.
Fixes #83
> Add build configure option --O3

- pkg/acs/calacs/calacs/acsmain.c
`calacs.e --version` now only reports the number. Added `calacs.e -r` to report version number and date.
Fix #75 
c/c @jamienoss
> Fix CALACS version reporting

- pkg/wfc3/calwf3/Dates
- pkg/wfc3/calwf3/History
- pkg/wfc3/calwf3/Updates
- pkg/wfc3/calwf3/include/wf3version.h
- pkg/wfc3/calwf3/wf3cte/wf3cte.c
Removed double statement, probably left over from last testing round. Quick data checks show correct and unchanged results.
> fixes #63, double statement

- wscript
This is such that one can at least begin to debug compiler optimized code.
Add -g to the list of compiler flags.
The build configure option --debug takes precedence over this one.
Fixes #79
> Add build configure option --release-with-symbols

- pkg/wfc3/calwf3/wf3cte/wf3cte.c
This updates the logic to be specific to the if loop it's contained in. The fix results in no data changes because the previous logic applied the gain correction to all pixels per the outside for loop.
> wfc3 cte specific logic update for issue #55

- hstio/hstio.c
- hstio/keyword.c
- include/hstio.h
- include/xtables.h
- pkg/acs/calacs/acs2d/doflat.c
- pkg/acs/calacs/acsrej/acsrej_loop.c
- pkg/stis/calstis/cs1/dobias.c
- pkg/stis/calstis/cs1/doblev.c
- pkg/stis/calstis/cs1/dodark.c
- pkg/stis/calstis/cs1/dodqi.c
- pkg/stis/calstis/cs1/doflat.c
- pkg/stis/calstis/cs1/dolores.c
- pkg/stis/calstis/cs1/doshad.c
- pkg/stis/calstis/cs4/maketemplate.c
- pkg/stis/calstis/cs6/do1dx.c
- pkg/stis/calstis/cs6/idtalg/calstis6idt.c
- pkg/stis/calstis/cs7/do2dx.c
- pkg/wfc3/calwf3/lib/dodqi.c
- pkg/wfc3/calwf3/wf3ccd/doccd.c
- pkg/wfc3/calwf3/wf3ccd/sink.c
- pkg/wfc3/calwf3/wf3cte/wf3cte.c
- pkg/wfc3/calwf3/wf3rej/rej_loop.c
- tables/c_tbcfnd1.c
- tables/c_tbegt.c
- tables/c_tbtclo.c
- tables/c_tbtopn.c
- wscript
This PR appends the boolean parameter 'zeroInitialize'
as an option to call ``malloc`` (false) rather than ``calloc`` (true)
for the following allocation rounties in hstio.c:
``` C
allocFloatData();
allocShortData();
allocHdr();
allocSingleGroup();
allocFloatHdrData();
allocShortHdrData();
```
It also adds the following new routines to hstio:
``` C
void copyDataSection(DataSection * dest, const DataSection * src);
int swapFloatStorageOrder(FloatTwoDArray * target, const FloatTwoDArray * source, enum StorageOrder targetStorageOrder);
int swapShortStorageOrder(ShortTwoDArray * target, const ShortTwoDArray * source, enum StorageOrder targetStorageOrder);
int copyFloatHdrData(FloatHdrData * target, const FloatHdrData * src, enum StorageOrder targetStorageOrder);
int …
```
> Infrastructure changes, inc. hstio

- ctegen2/ctegen2.c
- ctegen2/ctegen2.h
- pkg/acs/calacs/acscte/docte.c
This also allows the gen2 algorithm to be used as it
reverts "Short circuit CTE algorithm to the previous gen1 for initial 2017.2 release to DMS"
Resolves #110
> Update ACS gen2 CTE algorithm to version 1.2

- ctegen2/ctegen2.c
> Incorrectly positioned #endif in CTE smoothing

- ctegen2/ctehelpers.c
- pkg/acs/calacs/acscte/docte.c
This also corrects some trlmessages() being used as errors to trlerror
resolves #123
> ACS CTE: correct PCTETAB in corrected image file header from --pctetab <file>

- pkg/acs/calacs/acscte/dopcte-gen2.c
> ACS CTE Regression: gen2 error contribution incorrectly computed

- hstio/hstio.c
> PtrRegister aborts/crashed on addPtr() due to realloc mem not being allocated

- hstio/hstio.c
- include/hstio.h
> PtrRegister::freeReg() should NOT call freeAll()

- ctegen2/ctehelpers.c
fixes to #135
Requires #147 to be merged into candidate-1.2.0 and then up-merged into
candidate-1.3.0. Without #147 this change will segfault
> ACS CTE: allocateCTEParamsFast() needs to use free() & NOT delete()

- pkg/acs/calacs/Dates
- pkg/acs/calacs/History
- pkg/acs/calacs/Updates
- pkg/acs/calacs/include/acsversion.h
This updates the following files:
pkg/acs/calacs/Dates
pkg/acs/calacs/History
pkg/acs/calacs/Updates
pkg/acs/calacs/include/acsversion.h
resolves #146
> Bump ACS version to 9.2.0

- ctegen2/ctegen2.c
This should reduce possible runtimes being held up by contended cores when run as
the default 'greedy' mode.
resolves #152 
> Make main CTE loop over columns dynamic rather than static

- pkg/acs/calacs/acsccd/doccd.c
- pkg/acs/calacs/lib/acshist.c
Fix #172 
Follow-up of #64
Update -- Output with this fix will have the following in its primary header when SINKCORR is applied successfully:
```
SINKCORR= 'COMPLETE'           /                  
SNKCFILE= 'xxxxxxxx_snk.fits'     
...
HISTORY SINKCORR complete ...                                                   
HISTORY   reference image xxxxxxxx_snk.fits                                        
HISTORY     INFLIGHT 27/07/2016 22/08/2016                                      
HISTORY     Sink pixel reference file ---------------------------- 
```
> Update SINKCORR keyword and HISTORY when done

- pkg/acs/calacs/acscte/maincte.c
- pkg/acs/calacs/calacs/acsmain.c
resolves #169
Note: This also corrects the acscte syntax listing 'output' as optional
i.e. [output].
> ACS "unrecognised option" error should also print syntax

- pkg/acs/calacs/acsccd/doccd.c
- pkg/acs/calacs/acsrej/acsrej_do.c
- pkg/acs/calacs/lib/acshist.c
- pkg/acs/calacs/lib/imghistory.c
Addresses the prvious commit b6690fa5b18dab2fe1b46597c29bbc65b435271c
Update SINKCORR keyword and HISTORY when done
resolves #176
> Update SINKCORR keyword and HISTORY... address #173 code review

- include/dummy.h
- lib/dummy.c
- lib/wscript
- wscript
dummy.h & dummy.c will be removed upon next commit that actually populates
the lib.
resolves #188
> Create hstcal lib to pair with include

- pkg/acs/calacs/acs2d/main2d.c
- pkg/acs/calacs/acsccd/mainccd.c
- pkg/acs/calacs/acscte/maincte.c
- pkg/acs/calacs/acsrej/mainrej.c
- pkg/acs/calacs/acssum/mainsum.c
- pkg/acs/calacs/lib/trlbuf.c
- pkg/wfc3/calwf3/lib/trlbuf.c
- pkg/wfc3/calwf3/wf32d/main2d.c
- pkg/wfc3/calwf3/wf3ccd/mainccd.c
- pkg/wfc3/calwf3/wf3cte/maincte.c
- pkg/wfc3/calwf3/wf3ir/mainir.c
- pkg/wfc3/calwf3/wf3rej/mainrej.c
- pkg/wfc3/calwf3/wf3sum/mainsum.c
fixes #196
This also makes trlbuf.buffer and trlbuf.preface NULL after freed.
> Don't write to trailer file after trlbuf has been freed and file closed

- pkg/acs/calacs/acs2d/main2d.c
- pkg/acs/calacs/acsccd/mainccd.c
- pkg/acs/calacs/acscte/maincte.c
- pkg/acs/calacs/acssum/mainsum.c
- pkg/acs/calacs/calacs/acsmain.c
- pkg/stis/calstis/cs0/cs0.c
- pkg/stis/calstis/cs1/cs1.c
- pkg/stis/calstis/cs11/cs11.c
- pkg/stis/calstis/cs12/cs12.c
- pkg/stis/calstis/cs4/cs4.c
- pkg/stis/calstis/cs8/cs8.c
- pkg/wfc3/calwf3/calwf3/wf3main.c
- pkg/wfc3/calwf3/wf32d/main2d.c
- pkg/wfc3/calwf3/wf3ccd/mainccd.c
- pkg/wfc3/calwf3/wf3cte/maincte.c
- pkg/wfc3/calwf3/wf3ir/mainir.c
- pkg/wfc3/calwf3/wf3sum/mainsum.c
Add --help cmd option to print syntax
Resolves #238
Doesn't cover:
wf3rej.e
acsrej.e
cs2.e
cs6.e
AND
"unrecognized option" errors should also print syntax
Resolves #171
Doesn't cover:
wf3rej.e
acsrej.e
cs2.e
cs6.e
> Add --help cmd option to print syntax

- hstio/hstio.c
- include/hstio.h
- lib/trlbuf.c
- pkg/acs/calacs/calacs/calacs.c
- pkg/acs/calacs/lib/fileexists.c
- pkg/acs/calacs/lib/mkspt.c
- pkg/imphttab/test_getphttab.c
- pkg/stis/calstis/cs0/calstis0.c
- pkg/stis/calstis/cs1/doblev.c
- pkg/stis/calstis/cs4/calstis4.c
- pkg/wfc3/calwf3/calwf3/calwf3.c
- pkg/wfc3/calwf3/lib/fileexists.c
- pkg/wfc3/calwf3/lib/mkspt.c
- tables/tbl_util.c
Set error status on failed fclose
Resolves #226
AND
Guard fclose(std::FILE* stream) against stream == NULL
Fixes #252
> Resolve fclose() related bugs #226 & #252

- include/trlbuf.h
- lib/trlbuf.c
- pkg/acs/calacs/acs2d/main2d.c
- pkg/acs/calacs/acsccd/mainccd.c
- pkg/acs/calacs/acscte/maincte.c
- pkg/acs/calacs/acsrej/mainrej.c
- pkg/acs/calacs/acssum/mainsum.c
- pkg/acs/calacs/calacs/acsmain.c
- pkg/wfc3/calwf3/calwf3/wf3main.c
- pkg/wfc3/calwf3/wf32d/main2d.c
- pkg/wfc3/calwf3/wf3ccd/mainccd.c
- pkg/wfc3/calwf3/wf3cte/maincte.c
- pkg/wfc3/calwf3/wf3ir/mainir.c
- pkg/wfc3/calwf3/wf3rej/mainrej.c
- pkg/wfc3/calwf3/wf3sum/mainsum.c
Resolves #247
This faciltates TrlBuf objects being tracked by PtrRegister.
> CloseTrlBuf(void) -> CloseTrlBuf(struct TrlBuf * ptr)

- pkg/acs/calacs/lib/reffiles.c
- pkg/stis/calstis/cs12/cs12.c
- pkg/stis/calstis/cs6/cs6.c
- pkg/stis/calstis/lib/reffiles.c
- pkg/wfc3/calwf3/lib/reffiles.c
Fixes #280
This also addresses the "-Wmisleading-indentation" compiler warnings generated
from the following files, also from #275
pkg/stis/calstis/lib/reffiles.c
pkg/stis/calstis/cs12/cs12.c
pkg/acs/calacs/lib/reffiles.c
pkg/wfc3/calwf3/lib/reffiles.c
> Fix unguarded IFs introduced in #275

- pkg/acs/calacs/calacs/calacs.c
- pkg/acs/calacs/calacs/wscript
> Temporarily set PCTECORR to OMIT during non-CTE ACSrej so as not to use CTE dark

- ctegen2/ctegen2.h
- ctegen2/ctehelpers.c
- hstio/keyword.c
- include/hstio.h
- pkg/acs/calacs/acscte/docte.c
- pkg/acs/calacs/acscte/dopcte-gen2.c
- pkg/acs/calacs/include/acsversion.h
- pkg/acs/calacs/lib/acshist.c
ACS CTE: Use amp dependent RN from CCDTAB and not general RN from PCTETAB
Resolves #213
AND
Add updateKeyX() and updateKeyOrAddAsHistKeyX() functions
Resolves #270
> ACS CTE: Use amp dependent read-noise

- pkg/acs/calacs/calacs/acsdth.c
- pkg/acs/calacs/calacs/calacs.c
- pkg/acs/calacs/lib/mkspt.c
Improves error message for existing output association SPT file and warning messages
for individual input SPT files.  Also, now writes all existing input SPT arrays into
output association SPT file.
This fix potentially changes the output association SPT file. CALACS now writes all
existing input SPT arrays (extensions) into the output association SPT file.  Formerly,
if the first input SPT file named in the association table did not exist, no output
association SPT file would be written at all.  Also, if an input SPT file contained
multiple SPT arrays, only one of the arrays would be written to the output association
SPT file.
Resolves #199
Signed-off-by: Michele De La Pena <mdelapena@stsci.edu>
> CALACS: Clarifies error/warning messages for SPT files.

- pkg/acs/calacs/lib/acshist.c
Fixes #295
Regression introduced by #271
> Uninitialized variable yields undefined behavior for logging pctehistory keywords

- CODE_OF_CONDUCT.md
This adds a formal code of conduct to this repository. c/c @stsci-hack @eteq
> Add spacetelescope code of conduct to HSTCAL repo

- ctegen2/ctegen2.c
- ctegen2/ctegen2.h
- pkg/acs/calacs/acscte/acscte.c
- pkg/acs/calacs/acscte/docte.c
- pkg/acs/calacs/acscte/dopcte-gen2.c
- pkg/acs/calacs/acscte/forward_model/main.c
- pkg/acs/calacs/acscte/forward_model/wscript
- pkg/acs/calacs/acscte/main.c
- pkg/acs/calacs/acscte/maincte.c
- pkg/acs/calacs/acscte/wscript
- pkg/acs/calacs/calacs/calacs.c
- pkg/acs/calacs/wscript
The cmd line option ``--forwardModelOnly``
piggy-backs upon the normal CTE code and usage (gen2 only) however,
instead of correcting the CTE trails it actually simulates (adds) them.
All CTE flags and ref files must be defined in the exact same
manner needed to run the actual CTE correction.
``PCTECORR`` must be set to ``PERFORM``.
> ACS CTE: Add forward modeling functionality

- pkg/acs/calacs/acs2d/dodark.c
- pkg/acs/calacs/lib/findbin.c
- pkg/acs/calacs/lib/multk2d.c
- pkg/acs/calacs/lib/sub1d.c
- pkg/acs/calacs/lib/sub2d.c
- pkg/acs/calacs/lib/trim2d.c
- pkg/acs/calacs/lib/wscript
Addresses IT #314.
The dark correction algorithm has been modified to work directly on the full 2D data rather than on a line-by-line basis.  This is in preparation for the implementation of a new dark correction algorithm which accommodates a high-dynamic range dark.  The new algorithm is TBD by the ACS team.  At this stage, the known 2D modifications have been done and regression testing with a varied sample of 18 ACS datasets.  Please note there are still some print statements in the code being utilized for testing.  Also, there is an open question as to the exact computation wanted for the mean dark value.  This code only exists on my origin/hackday branch at this time.
> Modify the dark correction to work directly on the 2D image rather than line-by-line

- include/str_util.h
- lib/str_util.c
- lib/wscript
- pkg/acs/calacs/acs2d/acs2d.c
- pkg/acs/calacs/acsccd/acsccd.c
- pkg/acs/calacs/acscte/acscte.c
- pkg/acs/calacs/acsrej/acsrej_check.c
- pkg/acs/calacs/include/acsinfo.h
- pkg/acs/calacs/include/getacskeys.h
- pkg/acs/calacs/lib/getacskeys.c
Fixes regression introduced from #330
Includes refactoring of ``GetACSKeys()`` into 2 sep funcs
``getACSKeys()`` & ``checkACSKeys()``, the former doing only the literal
getting.
Fixes #333
Resolves #323
> Make acs->nimsets = findTotalNumberOfImsets() conditional on forwarModelOnly

- pkg/acs/calacs/lib/getacskeys.c
Fixes regression introduced from #335 
Fixes #333
Resolves #323
In refactoring a routine to separate "getting" from "checking", an uninitialized variable was used as the discriminant for executing an "if" block.
> Fix to use an existing variable in an if clause.

- Jenkinsfile
- JenkinsfileRT
- tests/helpers.py
- tests/stis/test_lev1_fuvspec.py
As discussed with @stsci-hack . For example, what if a developer wishes to run HSTCAL and CALCOS big data tests back to back without wanting to change `TEST_BIGDATA` in their bash startup script?
> Enable TEST_BIGDATA to be used across multiple repos

- Jenkinsfile
- JenkinsfileRT
Behavior of `--basetemp` flag in `pytest` appears to have changed in recently published `pytest 3.9.1`, breaking RT tests. Reverting to `3.8.2` works around the issue until the pytest situation is sorted out.
> Pin pytest to 3.8.2 to avoid  problem in 3.9.1; normalize package list.

- JenkinsfileRT
- tests/acs/test_hrc.py
- tests/acs/test_hrc_single.py
- tests/acs/test_wfc_sinkcorr.py
- tests/wfc3/test_uvis_01asn.py
- tests/wfc3/test_uvis_05asn.py
Created new truth files and uploaded the files to Artifactory.  As such, the `xfail` is obsolete.
> Remove pytest.mark.xfail (Git Issue#352)

- JenkinsfileRT
This matches the approach taken in `Jenkinsfile`.
> Use released ci-watson from conda, rather than master commit via pip.

- Jenkinsfile
- pkg/acs/calacs/Dates
- pkg/acs/calacs/History
- pkg/acs/calacs/Updates
- pkg/acs/calacs/acsrej/acsrej_do.c
- pkg/acs/calacs/acsrej/acsrej_loop.c
- pkg/acs/calacs/include/acsversion.h
Addresses IT #373.
The value of IMAGETYP is used to determine whether or not the data to be processed via ACSREJ is a set of BIAS or DARK images.  If BIAS or DARK images are processed, the DQ=4 value (Bad pixel detector) is ignored during the combination of the SCI and ERR extensions, though the DQ=4 value is present in the DQ extension of the final *_crj.fits file.  Results based upon the updates to the CALACS pipeline can be found in /user/mdelapena/acs where the asn, raw, and spt input files were provided by @nmiles2718.  Please see these files for correctness.  Also, my branch (issue373_bpixtab) can be accessed to allow you to process datasets yourself.  If you have any issues, please let me know.
> WIP - BPIXTAB: Do not use DQ=4 when combining BIAS or DARK images in ACSREJ.

- Jenkinsfile
- JenkinsfileRT
The change in https://github.com/spacetelescope/jenkins_shared_ci_utils/pull/52 moved the source tree cloned for the target project of the CI job into a `clone` subdir. This PR updates the `PATH` definition in `JenkinsfileRT` to allow the tests to execute.
> Fix PATH value to allow tests to run.

- Jenkinsfile
- JenkinsfileRT
- pytest.ini
`pytest >= 4.0` is required to allow `junit_family` to be specified in the pytest configuration so that test report XML will be produced in way that's compatible with Jenkins. Without specifying `junit_family = xunit2`, test results fail to be imported.
Addresses #372
> Unpin pytest

- tests/acs/test_hrc.py
- tests/acs/test_hrc_single.py
- tests/acs/test_sbc.py
- tests/acs/test_wfc_asn.py
- tests/acs/test_wfc_single.py
- tests/acs/test_wfc_sinkcorr.py
- tests/acs/test_wfc_sub.py
Updated the ACS tests to ignore a few additional keywords as the comment portion of the FITS cards do not match.
> Update ACS tests to ignore additional keywords

- pkg/acs/calacs/Dates
- pkg/acs/calacs/History
- pkg/acs/calacs/Updates
- pkg/acs/calacs/acs2d/photmode.c
- pkg/acs/calacs/acsrej/acsrej_loop.c
- pkg/acs/calacs/include/acsversion.h
CALACS has been modified to allow the PHOTMODE keyword to be appended with the MJD for the SBC, as is currently done for HRC and WFC. This will allow time-dependent sensitivity to be applied properly to SBC.
Testing was done before and after the fix.  Before the fix PHOTMODE would contain the following string in the first extension of the FLT:
jc3003qnq_flt.fits[1],PHOTMODE = "ACS SBC F150LP"
After the fix (testing was accomplished using a test IMPHTTAB provided by @rjavila):
jc3003qnq_flt.fits[1],PHOTMODE = "ACS SBC F150LP MJD#56392.6597"
> PHOTMODE keyword updated with MJD for SBC 

- Jenkinsfile
- JenkinsfileRT
- tests/conftest.py
We will eventually stop delivering conda packages for `ci-watson`. Just `pip install` it.
Resolves #464
> Switch to pip install of ci-watson and pytest in Jenkinsfiles

- pkg/acs/calacs/Dates
- pkg/acs/calacs/History
- pkg/acs/calacs/Updates
- pkg/acs/calacs/acs2d/dodark.c
- pkg/acs/calacs/include/acs.h
- pkg/acs/calacs/include/acsinfo.h
- pkg/acs/calacs/include/acsversion.h
- pkg/acs/calacs/lib/acsinfo.c
- pkg/acs/calacs/lib/getacskeys.c
- pkg/acs/calacs/lib/getccdtab.c
- tests/acs/test_wfc_darktime.py
This PR addresses Issue #326.  (FYI - @nmiles2718 @mmcdonald123)
Removed hard-coded darktime scaling value and read new post-flashed and unflashed columns from updated CCDTAB reference files (WFC and HRC) to use for the offset to the DARKTIME FITS keyword value under appropropriate date and supported subarray criteria.  The DARKTIME keyword value is now the default scaling factor for the superdarks (WFC, HRC, and SBC), with the offset being an additive correction to DARKTIME under appropriate circumstances.  The offset only applies to WFC and HRC.
This software update changes data and requires new reference files for WFC and HRC.
A new PyTest was created for regression testing of the new algorithm.
> Issue 326 darktime updates

- wscript
* This is compatible with Apple Clang
* (non-GNU) `strdup()` was producing garbage
Let's see if the tests fair better...
> Use -std=gnu99

- pkg/acs/calacs/Dates
- pkg/acs/calacs/History
- pkg/acs/calacs/Updates
- pkg/acs/calacs/include/acs.h
- pkg/acs/calacs/include/acsinfo.h
- pkg/acs/calacs/include/acsversion.h
- pkg/acs/calacs/lib/acsinfo.c
- pkg/acs/calacs/lib/dodqi.c
- pkg/acs/calacs/lib/getccdtab.c
- tests/acs/test_hrc_single.py
The new A-to-D saturation threshold is no longer a constant value and has different behavior pre- and post-SM4.  The CCDTAB files have been updated by the ACS team to contain a new column, ATODSAT, which contains the saturation threshold value.
Please be aware the old code compared a science pixel value to the saturation threshold as only **_greater than_**.  In contrast, the new code is **_greater than or equal to_** as specified in the issue.
This PR fixes Git Issue #460.
> Modified "dodqi" to accommodate the A-to-D saturation threshold

- pkg/stis/calstis/cs6/idtalg/calstis6idt.c
Fix a minor memory leak in `BuildTempNames`
> Free aname after use

- pkg/acs/calacs/lib/parsedate.c
Fixes minor memory leaks in `parseObsDate` and `parseTabDate`
> Free cp after use

- pkg/acs/calacs/acs2d/main2d.c
`acs2d.e` on `crj_tmp` input does not produce `crj` as expected. Without this patch, it produces `crj_tmp_flt`. I think I forgot to increase the counter all those years ago back in 510b2184682ede529e9a5.
For comparison, look at the correct counter deeper in the code here:
https://github.com/spacetelescope/hstcal/blob/f5680b59b8a1eeab3d92de708ea4a44c2dfe8550/pkg/acs/calacs/acs2d/acs2d.c#L190
Disclaimer: The code has changed enough since I last tried build it from source that now I am no longer able to build it successfully on my local Linux machine, so I am not sure how to test this patch. 🤷‍♀  (Also see #472)
> BUG: main2d not setting suffix correctly

- pkg/acs/calacs/acsrej/piksrt.c
Removed residue from the piksrt.c sort routines [trlmessage[MsgText)] which was causing memory issues as MsgText was undefined.
> Removed residue sort routine

- pkg/imphttab/getphttab.c
- pkg/wfc3/calwf3/Dates
- pkg/wfc3/calwf3/History
- pkg/wfc3/calwf3/Updates
- pkg/wfc3/calwf3/include/wf3version.h
- pkg/wfc3/calwf3/wf32d/dophot.c
- pkg/wfc3/calwf3/wf32d/photmode.c
- tests/wfc3/test_uvis_11single.py
- tests/wfc3/test_uvis_14single.py
- tests/wfc3/test_uvis_22single.py
imphttab
- Fixed an existing bug in getphttab.c by ensuring a string was set to
the empty string.  The bug would only be manifested for multiple Imsets
in an input file, in conjunction with a parameterized value.
wfc3
- Added MJD as a parameterized variable for the PHOTMODE keyword to
enable a time-dependent photometric correction for the UVIS only.
- Removed appending "CAL" to the PHOTMODE keyword.
> WFC3 Time-dependent photometry update

- tests/stis/test_lev1_fuvspec.py
- tests/wfc3/test_uvis_01asn.py
- tests/wfc3/test_uvis_05asn.py
- tests/wfc3/test_uvis_32single.py
Add the xfail marker to the CTE WFC3 tests as they cannot pass at this time.  The input and truth files have already been updated on Artifactory, but the new code which mates with these files has not been merged.  Add skip to the STIS test as the situation is not clear. There have been no commits to STIS software.
> Add xfail or skip to PyTests

- tests/stis/test_lev1_fuvspec.py
The import statement for pytest was added to the test in order to allow the test to be marked properly for skipping (pytest.mark.skip).
> Added missing import for pytest to the STIS test

- pkg/acs/calacs/acs2d/dodark.c
- pkg/acs/calacs/acsccd/doccd.c
Added explicit declaration of subroutine, doFullWellSat() in doccd.c (new code).  Added explicit inclusion of the string library in an old routine, dodark.c.
> Fix explicit declaration of routine and include header

- pkg/acs/calacs/acscte/maincte.c
- pkg/acs/calacs/include/acsversion.h
Removed parameter being passed to static function printSyntax() as it is incorrect and may be causing serious problems 
(segfault) on some systems with acscte.e. Incremented the calacs version.
> Removed parameter being passed to static function printSyntax()

- pkg/acs/calacs/acscte/maincte.c
Fixed the check on argv[0] to ensure the variable "program" always contains the base program name.  This cures the seg fault generated on the build machines.
> Fixed the check on argv[0]

- pkg/wfc3/calwf3/Dates
- pkg/wfc3/calwf3/History
- pkg/wfc3/calwf3/Updates
- pkg/wfc3/calwf3/include/wf3version.h
- pkg/wfc3/calwf3/wf3cte/wf3cte.c
Bug fix to address a problem detected when processing a Tungsten flat with a high background… with a high background.
Uninitialized values were used for further computation causing an eventual exception.  The problem detected by this image could happen for images with lower backgrounds with no pixel values less than a threshold minimum (1000) so
it was important to fix for useful science data.
> Bug fix to address a problem detected when processing a Tungsten flat with a high background

- pkg/acs/calacs/Dates
- pkg/acs/calacs/History
- pkg/acs/calacs/Updates
- pkg/acs/calacs/acscte/maincte.c
- pkg/acs/calacs/acscte/wscript
- pkg/acs/calacs/include/acsversion.h
The name of a standalone executable inadvertently was changed when code was re-arranged by the build manager to address circular references. Changed acsforwardmodel.e back to acscteforwardmodel.e
to aid documentation and script issues.
> Fix the name of the standalone executable acscteforwardmodel.e

- pkg/acs/calacs/Dates
- pkg/acs/calacs/History
- pkg/acs/calacs/Updates
- pkg/acs/calacs/acsrej/acsrej_check.c
- pkg/acs/calacs/acsrej/acsrej_do.c
- pkg/acs/calacs/include/acsversion.h
Fixed a bug associated with the FLASHDUR computation.  The FLASHDUR keyword was updated in the CRJ/CRC headers to be the sum of the individual input images as this keyword is used in ACS2D to scale the flash reference file for flash correction.
> Issue489 fixflash

- pkg/acs/calacs/Dates
- pkg/acs/calacs/History
- pkg/acs/calacs/Updates
- pkg/acs/calacs/acs2d/dodark.c
- pkg/acs/calacs/acsccd/dobias.c
- pkg/acs/calacs/acsccd/doccd.c
- pkg/acs/calacs/acsrej/acsrej_check.c
- pkg/acs/calacs/acsrej/acsrej_do.c
- pkg/acs/calacs/include/acsversion.h
Fixed a bug associated with the DARKTIME computation Code written for CALACS 10.2.2 was moved from ACS2D to ACSCCD so every BLV_TMP file has the correct DARKTIME keyword value.  Also, the DARKTIME keyword was updated in the CRJ/CRC
headers to be the sum of the individual input images. Only the DARKTIME value in the input file header is used to scale the dark reference file for the dark correction.
This PR fixes Git Issue#490.
> Fixed a bug associated with the DARKTIME computation and utilization

- pkg/wfc3/calwf3/Dates
- pkg/wfc3/calwf3/History
- pkg/wfc3/calwf3/Updates
- pkg/wfc3/calwf3/include/wf3version.h
- pkg/wfc3/calwf3/wf3ir/groupinfo.c
Nor identified a problem with calwf3.e that cropped up during one of the last rewrite: It is no longer possible to process a raw dataset, and then take an ima and **_finish the processing_** with calwf3. This is a feature fundamental to being able to remove the variable IR background during the course of an exposure. The errors I see are just binary -6 errors. Turning on flatcorr when producing the IMA file and CRCORR off works but feeding an IMA processed this way and turning on CRCORR does not and exits with a -6 error code. 
I hope this can be resolved because it is stopping a few of us from progressing with out IR slitless data reduction.
> WFC3 aborts when processing IR IMA file with CRCORR=PERFORM

- pkg/acs/calacs/acsccd/mainccd.c
Fix #554 by exiting "gracefully" and giving more useful hint on why it failed. With this patch:
```
ERROR: Input path exceeds maximum supported length (255)
syntax:  acsccd [--help] [-t] [-v] [-q] [--version] [--gitinfo] input output
```
Out of scope: I have no WBS to charge to, so I cannot apply this to CALACS globally. This PR is only meant to solve the immediate problem reported originally over at ACSTOOLS.
> Use strncpy for inlist in acsccd.e, better error

- pkg/acs/calacs/Dates
- pkg/acs/calacs/History
- pkg/acs/calacs/Updates
- pkg/acs/calacs/acsccd/doccd.c
- pkg/acs/calacs/include/acsversion.h
Fixed a bug which was triggered ONLY when executing the condaforge
distribution on MacOS where failure was due to a missing return statement.
Only call computeDarktime() once to compute the updated
DARKTIME primary keyword and function return is now void. Update
the keyword in main to avoid passing extra data by reference.
> Fixed bug triggered ONLY when executing the condaforge on MacOS

- pkg/acs/calacs/Dates
- pkg/acs/calacs/History
- pkg/acs/calacs/Updates
- pkg/acs/calacs/acsrej/acsrej_do.c
- pkg/acs/calacs/acsrej/acsrej_loop.c
- pkg/acs/calacs/include/acsversion.h
Update to the cosmic ray rejection algorithm as to the way the output ERR extension is computed for the CRJ/CRC file. The output ERR is now propagated from the usable input ERR extensions versus being computed by a model.
Resolves #371.
> ACSREJ algorithm modified for ERR array

- wscript
This change covers an edge case for when `./waf dist` is executed from a branch outside of `master` and no tag is associated with the current commit it returns `UNKNOWN`. All this does is add fallback behavior to ensure `VERSION` gets populated with the closest parent tag rather than `UNKNOWN`.
> Fix dist tag resolution

- wscript
If there's no PATCH version available then handle it.
Close #570
> wscript: Fix _check_mac_osx_version() on modern MacOS systems

- pkg/wfc3/calwf3/wf3cte/maincte.c
Updated syntax string of the main wf3cte module, fixed the output for the "--version" option, and fixed some internal comments.
> Correct syntax string of the main wf3cte module

- tests/wfc3/test_uvis_01asn.py
- tests/wfc3/test_uvis_06single.py
- tests/wfc3/test_uvis_07single.py
- tests/wfc3/test_uvis_10single.py
- tests/wfc3/test_uvis_12single.py
- tests/wfc3/test_uvis_13single.py
- tests/wfc3/test_uvis_16single.py
- tests/wfc3/test_uvis_26single.py
- tests/wfc3/test_uvis_28single.py
- tests/wfc3/test_uvis_29single.py
- tests/wfc3/test_uvis_30single.py
- tests/wfc3/test_uvis_33single.py
Set certain WFC3/UVIS tests to XFAIL as the truth files on Artifactory have been updated for the new software, but this software is NOT being delivered as part of the build (HSTDP-2023.1.0) to operations.
The issue is there are many packages which are part of the "operations build".  In order for the nightly regression tests to pass, when new software is checked in, the corresponding Truth files on Artifactory must be updated.  However, if the software is not to be included in the next build to be delivered, the PyTests for this package will fail as there is only one source of Input and Truth files.  
This means there must be manual gating of the packages which contribute to the build which is not realistic.
> Set certain WFC3/UVIS tests to XFAIL

- pkg/wfc3/calwf3/Dates
- pkg/wfc3/calwf3/History
- pkg/wfc3/calwf3/Updates
- pkg/wfc3/calwf3/include/wf3info.h
- pkg/wfc3/calwf3/include/wf3version.h
- pkg/wfc3/calwf3/lib/dodqi.c
- pkg/wfc3/calwf3/lib/getccdtab.c
- pkg/wfc3/calwf3/lib/getrefname.c
- pkg/wfc3/calwf3/lib/wf3info.c
- pkg/wfc3/calwf3/wf3ccd/doccd.c
- pkg/wfc3/calwf3/wf3ccd/dofwsat.c
- pkg/wfc3/calwf3/wf3ccd/getflags.c
Completed implementation to use an image to detect and flag full-well saturation versus a simple scalar.  The new routine, dofwsat.c, is similar to what has been done for calacs. The WFC3 implementation is more complicated in that there are serial virtual overscan columns, as well as binned images, to accommodate.  The detection/flagging occurs after blev and bias corrections while the output is still in counts.  If the SATUFILE keyword is missing from the FITS header, or the keyword does not have a valid filename as a value, the code will revert to using the original method of flagging full-well saturation.  The flagging will be done in doDQI and use a single value as the saturation threshold.
> Implement new (via image) and maintain old (scalar) saturation image flagging

- tests/wfc3/test_uvis_01asn.py
- tests/wfc3/test_uvis_06single.py
- tests/wfc3/test_uvis_07single.py
- tests/wfc3/test_uvis_10single.py
- tests/wfc3/test_uvis_12single.py
- tests/wfc3/test_uvis_13single.py
- tests/wfc3/test_uvis_16single.py
- tests/wfc3/test_uvis_26single.py
- tests/wfc3/test_uvis_28single.py
- tests/wfc3/test_uvis_29single.py
- tests/wfc3/test_uvis_30single.py
- tests/wfc3/test_uvis_33single.py
Tests which use input and truth that contain the new SATUFILE keyword had been set to skip.  These files can now be executed.
> WFC3: Removed skip from tests which will use inputs with the new SATUFILE

- pkg/wfc3/calwf3/wf3ccd/getflags.c
The GetFlags() in getflags.c did not properly handle when BIASCORR != PERFORM.  No warning message was issued, but more importantly, the scalar_satflag was not set to True, causing full-well saturation not to be flagged at all.
> Fix BIASCORR checking.

- pkg/wfc3/calwf3/wf3ccd/getflags.c
Added more handling for a BIASFILE with bad pedigree as the new full-well saturation algorithm using an image requires BLEVCORR and BIASCORR to be performed.  While the pedigree of the BIASFILE was always checked, if the pedigree were bad (or dummy), this was not an error.  This just meant the BIASCORR would be set to SKIPPED.  Due to the new saturation algorithm, the BIASCORR will still be SKIPPED, but the full-well saturation flagging will revert to the original algorithm to using a single scalar value as the flagging threshold performed in DODQI.
> HSTCAL: Handle BIASFILE with bad pedigree 

- pkg/wfc3/calwf3/Dates
- pkg/wfc3/calwf3/History
- pkg/wfc3/calwf3/Updates
- pkg/wfc3/calwf3/include/wf3version.h
- pkg/wfc3/calwf3/lib/computelimits.c
- pkg/wfc3/calwf3/lib/dodqi.c
- pkg/wfc3/calwf3/lib/wscript
- pkg/wfc3/calwf3/wf32d/do2d.c
- pkg/wfc3/calwf3/wf3ccd/doccd.c
- pkg/wfc3/calwf3/wf3ccd/doccd.h
- pkg/wfc3/calwf3/wf3ccd/dofwsat.c
- pkg/wfc3/calwf3/wf3ccd/findover.c
The WFC3 team realized the new way of flagging full-well saturated data using an image after the BLEVCORR/BIASCORR steps and the old way of flagging the data in DQICORR needed to be reconciled to account properly for any pixels which should have been flagged in the overscan regions. The overscan regions are trimmed in BLEVCORR/BIASCORR. The changes incorporated by the PR address this issue.
1. The ComputeLimits function has been pulled from being a part of the dofwsat.c file to be its own file, /lib/computelimits.c, so it is available to other files.
2. wscript file has been updated to include the new computelimits.c file.
3. The findover.c file was reformatted as it was too difficult to trace through the code and understand the flow. There were no actual code changes.
4. A parameter (int …
> HLA-1136: Flag full-well saturated pixels in the overscan regions in DQICORR

- pkg/acs/calacs/acs2d/do2d.c
- pkg/acs/calacs/lib/acsinfo.c
- pkg/acs/calacs/lib/tabpedigree.c
Addressed Jira Ticket: HLA-1178
Fixed the bug where the structure associated with the SPOTTAB variables was not initialized.  Also, fixed the issue where the PEDIGREE and DESCRIP keywords were deliberately being read from the wrong HDU.  Only in the case of tabular reference files were the mentioned keywords being read from the wrong HDU.  Fixed so the keywords are now being read from the primary HDU and properly logged to the trailer file.
> HLA-1178:  Garbled text reported in trailer file causes failure in Cloud processinge

- lib/trlbuf.c
Reported by @mdlpstsci
```
End      13-Feb-2024 17:18:56 EST
*** WF3CCD complete ***
End      13-Feb-2024 17:18:58 EST
*** CALWF3 complete ***
CALWF3 completion for some_file.fits
Segmentation fault: 11
```
Trace session
```shell
lldb -- calwf3.e some_file.fits
```
```gdb
(lldb) r
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
frame #0: 0x000000010048a750 libhstcalib.dylib`CloseTrlBuf(buf=0x0000000100008190) at trlbuf.c:606:9
603 	    FILE *ofp;
604
605 	    /* Do we have any messages which need to be written out? */
-> 606 	    if (buf->buffer[0] != '\0') {
607 	        /* We do, so open last known trailer file and
608 	            append these messages to that file...
609 	        */
Target 0: (calwf3.e) stopped.
(lldb) v
(TrlBuf *) buf …
```
> CloseTrlBuf: Prevent testing for empty message when buf->buffer is NULL

- .github/workflows/cmake.yml
Looks like your workflow using outdated checkout.
Ehem, @jhunkeler , where is the matrix for OSX ARM?
* https://github.com/actions/runner-images/issues/9254
> MNT: Bump checkout version

- pkg/wfc3/Dates
- pkg/wfc3/History
- pkg/wfc3/Updates
- pkg/wfc3/include/wf3version.h
- pkg/wfc3/lib/wf32d/photmode.c
Add the 'MJD#' value to the PHOTMODE keyword in order to enable a time-dependent photometric correction for the IR.  By adding the 'MJD#' value to the PHOTMODE keyword string value, the algorithm now must search the new IMPHTTAB file for a row whose first column, OBSMODE, matches the string. This supplements the change done previously for the UVIS in 2020.
> WIP: HLA-1036: An 'MJD#' value is added to the PHOTMODE keyword in the PHDU

- pkg/wfc3/Dates
- pkg/wfc3/History
- pkg/wfc3/Updates
- pkg/wfc3/include/wf3version.h
- pkg/wfc3/lib/wf32d/photmode.c
This commit was pushed to main prematurely, and the repository is now being prepared for a build.
Revert "WIP: HLA-1036: An 'MJD#' value is added to the PHOTMODE keyword in the PHDU (#612)"
This reverts commit 0276e46c51512eb4969a86004642c8bb2add703e.
> Revert commit 0276e46 as it was pushed prematurely

- JenkinsfileRT
This change avoids the following error produced by the delivery system when `hstcal` is tested _before_ any Python packages have been installed.
```
FileNotFoundError: [Errno 2] No such file or directory: 'pytest'
script returned exit code 1
```
> Move test dependency installation to test_cmds list

- tests/helpers.py
The helpers.py module uses **ci-watson** utilities to assist in the functionality of the **hstcal** PyTests.  A new version of **ci-watson** was released to PyPi today (09 July 2024), and the function signature of download_crds() has changed.  This PR addresses this change.
> Update call to download_crds() to accommodate new function signature

- pkg/acs/CMakeLists.txt
The link wrapper for `acscteforwardmodel.e` was lost when I ported hstcal from WAF to CMake.
The wrapper is used by the following code:
https://github.com/spacetelescope/hstcal/blob/main/pkg/acs/lib/acscte/domaincte.c#L155-L157
My apologies, @mdlpstsci!
> Restore acscteforwardmodel.e hardlink to acscte.e

- pkg/wfc3/Dates
- pkg/wfc3/History
- pkg/wfc3/Updates
- pkg/wfc3/include/wf3version.h
- pkg/wfc3/lib/wf32d/photmode.c
Allow MJD as a parameterized variable for the PHOTMODE keyword to enable a time-dependent photometric correction for the IR detector.  This change supplements the change done for the UVIS in 2020 (Version 3.5.2).
Regression tests for the WFC3 IR change were successfully run here as the RAW an TRUTH files were updated appropriately: https://plwishmaster.stsci.edu:8081/job/RT/job/HSTCAL-Developers-Pull-Requests/39/consoleText
Any ACS failures are because the RAW and TRUTH files were also updates to accommodate the ACS serial CTE update where the team needs to give the final approval.
> HLA-1310: Changes to accommodate an IR time-dependent IMPHTTAB

- .github/workflows/cmake.yml
- .github/workflows/open_actions_pr.yml
As recommended by https://scientific-python.org/specs/spec-0008/#pin-github-actions-release-workflows-to-their-full-release-commit-shas , this PR changes your Actions workflow version pins to hashes, and updates to latest release hashes (at the time of writing) if needed.
This is an automated update made by the `batchpr` tool :robot: - feel free to close if it doesn't look good! You can report issues to @pllim.
[:ghost:](https://github.com/pllim/playpen/issues/60)
> MNT: Use hash for Action workflow versions and update if needed

- pkg/acs/CMakeLists.txt
This PR corrects the following error when compiled using more than one make job:
```
+ make -j16
failed to create hard link because source path 'acscte.e' does not exist
```
> cmake: Ensure hardlink creation occurs after linking

- .github/workflows/cmake.yml
This is so commit spam won't result in long CI queue.
CI failure unrelated: https://github.com/spacetelescope/hstcal/issues/631
> TST: Cancel duplicate workflow runs

- pkg/acs/lib/calacs/acstable.c
* Fixes invalid heap access when `asn->numprod` is `>1`
```
../tests/acs/test_hrc.py::TestMosaic::test_4point_mosaic git tag: 3.1.0-10-g5c16e365-dirty
git branch: sprintf-to-snprintf
HEAD @: 5c16e365655e32b193c28192403af69788e4e8bf
Setting max threads to 16 out of 16 available
CALBEG*** CALACS -- Version 10.4.0 (07-May-2024) ***
Begin    18-Apr-2025 10:45:28 EDT
Input    j6m901020_asn.fits
Processing FULL ASN table...
LoadAsn:  Processing FULL Association
Trying to open j6m901020_asn.fits...
Read in Primary header from j6m901020_asn.fits...
=================================================================
==782080==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x516000000434 at pc 0x7b584bb69cd2 bp 0x7ffd8fdf6820 sp 0x7ffd8fdf6810
WRITE of size 4 at 0x516000000434 thread T0
#0 …
```
> allocAsnInfo: Allocate the product array using the number of products

- hstio/hstio.c
```
warning: allocation of insufficient size ‘8’ for type ‘Hdr’ with size ‘16’ [-Walloc-size]
```
```
*** ACSCCD complete ***
CALBEG*** ACS2D -- Version 10.4.0 (07-May-2024) ***
Begin    18-Apr-2025 11:46:34 EDT
Input    j6m901bzq_blv_tmp.fits
Output   j6m901bzq_flt.fits
Trying to open j6m901bzq_blv_tmp.fits...
Read in Primary header from j6m901bzq_blv_tmp.fits...
APERTURE HRC
FILTER1 F850LP
FILTER2 CLEAR2S
DETECTOR HRC
Processing 1 IMSETs... 
Imset 1  Begin 11:46:34 EDT
CCDTAB   44h17142j_ccd.fits
CCDTAB   PEDIGREE=inflight
CCDTAB   DESCRIP =CCD table
CCDTAB   DESCRIP =June 2002
DQICORR  OMIT
DARKCORR PERFORM
DARKFILE n3o1205tj_drk.fits
DARKFILE PEDIGREE=INFLIGHT 27/04/2002 21/05/2002
DARKFILE DESCRIP =Superdark created by Doug Van Orsow from proposal 9647
Darktime from header 0.000000 …
```
> allocSingleGroupHeader: Allocate size of the struct, not the pointer

- pkg/acs/lib/acscte/docte.c
* `doPCTEGen3` expects `ccdamp` to be a pointer to char (`char  *`)
This PR fixes the following:
```
docte.c:454:104: warning: passing argument 6 of ‘doPCTEGen3’ from incompatible pointer type [-Wincompatible-pointer-types]
454 |                         if ((status = doPCTEGen3(&acs[i], &ctePars, &x[i], forwardModelOnly, corrType, &ccdamp, nthAmp, amploc, ampID)))
|                                                                                                        ^~~~~~~
|                                                                                                        |
|                                                                                                        char (*)[(0, 2)]
```
Modern GCC and CLang both promote this warning to an error.
> Fixes incompatible pointer type error

- .github/workflows/cmake.yml
- CMakeLists.txt
- INSTALL.md
Allows one to enable the detection of leaks, overflows, and many other violations.
> cmake: Add option to enable AddressSanitizer

- .github/workflows/docker.yml
```
Error: 
Problem 1: cannot install the best candidate for the job
- nothing provides libgomp = 14.3.1-2.1.el10 needed by gcc-14.3.1-2.1.el10.x86_64 from appstream
- nothing provides libgcc >= 14.3.1-2.1.el10 needed by gcc-14.3.1-2.1.el10.x86_64 from appstream
Problem 2: cannot install the best candidate for the job
- nothing provides libstdc++ = 14.3.1-2.1.el10 needed by gcc-c++-14.3.1-2.1.el10.x86_64 from appstream
Problem 3: cannot install the best candidate for the job
- nothing provides libquadmath = 14.3.1-2.1.el10 needed by gcc-gfortran-14.3.1-2.1.el10.x86_64 from appstream
- nothing provides libgfortran = 14.3.1-2.1.el10 needed by gcc-gfortran-14.3.1-2.1.el10.x86_64 from appstream
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best …
```
> CI: Disable Stream 10 docker image

- .gitignore
- pkg/acs/include/acs.h
- pkg/acs/lib/CMakeLists.txt
- pkg/acs/lib/acsccd/blev_func_main.c
- pkg/acs/lib/acsccd/dobiasshift.c
- pkg/acs/lib/acsccd/doblev.c
- pkg/acs/lib/acsccd/doccd.c
- pkg/acs/lib/acsccd/dodarktime.c
Fix https://github.com/spacetelescope/hstcal/issues/668 . I don't think it needs a change log because if done properly, user should see no difference. 🤞 
RT: https://github.com/spacetelescope/RegressionTests/actions/runs/16435883013/job/46445714822
This is https://github.com/spacetelescope/hstcal/pull/673 with branch name that won't crash regtest Sonar scan.
- ???
- Profit!!!
> RFC: Move bias shift code out of doccd.c (try 2)

- CMakeLists.txt
You would think `snprintf` would be declared by `stdio.h` but apparently that's not always the case. :apple:
> cmake: Use check_function_exists for functions
